pipeline {
  agent any
  tools {
    nodejs 'node-11.0.0'
  }

  options {
    timeout(time: 2, unit: 'MINUTES')
  }

  stages {
    stage('Install dependencies') {
      steps {
        sh 'cd jenkins-tests && npm i'
      }
    }
    stage('Run tests') {
      steps {
        sh 'cd jenkins-tests && npm t'
      }
    }
    stage('run remote') {
        steps {
            build job: 'parameters', parameters: [string(name: 'ROOT_ID', value: '$BUILD_ID')], wait: true
        }
    }
  }
}
